# Site Settings
title: Aristel for github
email: msj351@naver.com
description: Some text about your blog.
baseurl:
#url: "https://www.rossener.com" # the base hostname & protocol for your site
url: "https://minsjang.github.io"
google_analytics: "UA-109411419-1"

# User Settings
username: Aristel
user_description: Hi~ Nice meet you (user_description)
disqus_username: disqus_username (disqus_username)

# Social Media
# Remove the item if you don't need it
github_username: MinSJang
facebook_username: Aristels
twitter_username: 
instagram_username: 
linkedin_username: 
medium_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

disqus-shortname: MinSJang

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home1
    url: /
  - title: About1
    url: /about/
  - title: Contact1
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

